### ISSUE TITLE
Website Braflix

### ISSUE THREAD

**Issue by LeGenDaRy15PT** [recloudstream/extensions#12]
A complete website with multi languages, especially me who is from Portugal and does not have any extensions, this website would be good to implement.

Braflix:
![image](https://github.com/recloudstream/extensions/assets/127091305/8f6a8165-21ea-4157-887d-1c37b30565fc)
![image](https://github.com/recloudstream/extensions/assets/127091305/f257ff51-a914-4f77-9e42-bf4b2fa379fa)
![image](https://github.com/recloudstream/extensions/assets/127091305/bc19256b-eceb-4a9d-9937-8ceb13cb8842)
![image](https://github.com/recloudstream/extensions/assets/127091305/28d65897-b3f2-4243-b158-e8439e8caddf)
![image](https://github.com/recloudstream/extensions/assets/127091305/f0293365-2ee0-4723-996e-3ec85871337f)

**Comment by ThatOneCalculator** [comment]
CloudStream doesn't support the distribution of pirated media. You should turn to *not officially supported **third party** plugins* for adding a source like that.

**Comment by C10udburst** [comment]
we do not support piracy.
