### ISSUE TITLE
Invidious Not Working

### ISSUE THREAD

**Issue by DarkCrypt** [recloudstream/extensions#2]
The Invidious instance is dead, YouTube is blocking it. I cloned the site in app to a different instance and that one works.

Learn more at issue: [#3822](https://github.com/iv-org/invidious/issues/3822)

**Comment by ArjixWasTaken** [comment]
YouTube is getting aggressive with the blocking it seems, but the folks over at invidious are making a tool to rotate their IPs every day or smth like that, so when that comes out it should be ok.

**Comment by DarkCrypt** [comment]
Right, I noticed YouTube has been stepping up their blocking strategy all around. I assume they're trying to maintain their dominance and massive ad revenue, obviously.

I figured you guys already knew about this issue. I appreciate what all the contributing devs have done in the past and will do in the future. Thank you for keeping CloudStream alive as much as possible.
