### ISSUE TITLE
AnimeWorld India is not working 

### ISSUE THREAD

**Issue by Shoaib12564** [recloudstream/extensions#3]
checked that the following extensions work on aniyomi

AnimeWorld India extension opens but cannot play any anime as seen attached in the images![Screenshot_20231029-232446_CloudStream Beta.png](https://github.com/recloudstream/extensions/assets/149332844/9399dc19-1a04-40a1-bc14-9d17b959bcac)

**Comment by C10udburst** [comment]
this repo is only for the invidious extension
