### ISSUE TITLE
Kayoanime is not working 

### ISSUE THREAD

**Issue by Shoaib12564** [recloudstream/extensions#4]
Kayoanime is working because there is no way to add Google Drive on cloudstream only showing coming soon....

![Screenshot_20231029-100339_CloudStream Beta.png](https://github.com/recloudstream/extensions/assets/149332844/00630b11-3d07-4ae0-9bbb-0bc0debd50a2)

It works fine on aniyomi
Can you add a web view option just like Aniyomi

**Comment by C10udburst** [comment]
this repo is only for the invidious extension
